Style/OpenStructUse:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Lint/SafeNavigationChain:
  Exclude:
    - lib/tasks/migrate.rake

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - app/models/decidim/initiative.rb
