# frozen_string_literal: true

require "extends/controllers/decidim/meetings/meetings_controller_extends"
require "extends/commands/decidim/initiatives/create_initiative_extends"
require "extends/commands/decidim/create_registration_extends"
require "extends/controllers/decidim/initiatives/create_initiative_controller_extends"
require "extends/controllers/decidim/initiatives/initiatives_controller_extends"
require "extends/helpers/decidim/initiatives/initiative_helper_extends"
require "extends/helpers/decidim/icon_helper_extends"
require "extends/commands/decidim/initiatives/admin/update_initiative_answer_extends"
require "extends/queries/decidim/initiatives/organization_prioritized_initiatives_extends"
require "extends/cells/decidim/initiatives/content_blocks/highlighted_initiatives_settings_form_cell_extends"
require "extends/commands/decidim/initiatives/update_initiative_extends"
require "extends/controllers/decidim/devise/account_controller_extends"
require "extends/commands/decidim/admin/update_organization_appearance_extends"
require "extends/cells/decidim/verifications/authorization_metadata_cell_extends"
require "extends/commands/decidim/verifications/authorize_user_extends"
