# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks

# The "main" locale.
base_locale: en

## Reporting locale, default: en. Available: en, ru.
# internal_locale: en

# Read and write translations.
data:
  ## Translations are read from the file system. Supported format: YAML, JSON.
  ## Provide a custom adapter:
  # adapter: I18n::Tasks::Data::FileSystem

  # Locale files or `File.find` patterns where translations are read from:
  read:
    - config/locales/%{locale}.yml

  # Locale files to write new keys to, based on a list of key pattern => file rules. Matched from top to bottom:
  # `i18n-tasks normalize -p` will force move the keys according to these rules
  write:
    - config/locales/%{locale}.yml

  ## Specify the router (see Readme for details). Valid values: conservative_router, pattern_router, or a custom class.
  # router: convervative_router

  yaml:
    write:
      # do not wrap lines at 80 characters
      line_width: -1

  ## Pretty-print JSON:
  # json:
  #   write:
  #     indent: '  '
  #     space: ' '
  #     object_nl: "\n"
  #     array_nl: "\n"

# Find translate calls
search:
  ## Paths or `File.find` patterns to search in:
  paths:
    - app
    - lib

  # Root directories for relative keys resolution.
  relative_roots:
    - app/controllers
    - app/helpers
    - app/mailers
    - app/presenters
    - app/services
    - app/views
    - app/cells

  ## Files or `File.fnmatch` patterns to exclude from search. Some files are always excluded regardless of this setting:
  ##   %w(*.jpg *.png *.gif *.svg *.ico *.eot *.otf *.ttf *.woff *.woff2 *.pdf *.css *.sass *.scss *.less *.yml *.json)
  exclude:
    - "*.jpeg"
    - "*.odt"
    - "*.docx"
    - "*.deface"

  ## Alternatively, the only files or `File.fnmatch patterns` to search in `paths`:
  ## If specified, this settings takes priority over `exclude`, but `exclude` still applies.
  # only: ["*.rb", "*.html.slim"]

  ## If `strict` is `false`, guess usages such as t("categories.#{category}.title"). The default is `true`.
  strict: false

  ## Multiple scanners can be used. Their results are merged.
  ## The options specified above are passed down to each scanner. Per-scanner options can be specified as well.
  ## See this example of a custom scanner: https://github.com/glebm/i18n-tasks/wiki/A-custom-scanner-example

## Google Translate
# translation:
#   # Get an API key and set billing info at https://code.google.com/apis/console to use Google Translate
#   api_key: "AbC-dEf5"

translation:
  deepl_api_key: <%= ENV["DEEPL_API_KEY"] %>

# Do not consider these keys missing:
ignore_missing:
 - faker.*
 - decidim.devise.shared.omniauth_buttons.or
 - devise.shared.links.sign_in_with_provider
 - layouts.decidim.header.user_menu
 - decidim.initiatives.initiatives.index_header.new_initiative
 - decidim.initiatives.admin.content_blocks.highlighted_initiatives.order.*
 - decidim.initiatives.create_initiative.fill_data.*
 - decidim.initiatives.form.*
 - layouts.decidim.header.user_menu
 - decidim.devise.shared.omniauth_buttons.or
 - devise.shared.links.sign_in_with_provider
 - decidim.initiatives.initiatives.print.print
 - decidim.initiatives.initiatives.show.{any_vote_method,offline_method,edit,send_to_technical_validation,confirm,follow_description}
 - decidim.proposals.omniauth.france_connect.external.{link,text}
 - decidim.proposals.omniauth.france_connect.forgot_password.ok_text
 - decidim.initiatives.initiatives.show.illegal.{title,description}
 - decidim.initiatives.create_initiative.select_initiative_type.*
 - decidim.admin.organization_appearance.form.images.*

# Consider these keys used:
ignore_unused:
  - faker.*
  - activemodel.attributes.osp_authorization_handler.*
  - activemodel.attributes.participatory_process.private_space
  - decidim.amendments.emendation.announcement.evaluating
  - decidim.authorization_handlers.osp_authorization_handler.{explanation, name}
  - decidim.authorization_handlers.osp_authorization_handler.fields.*
  - decidim.authorization_handlers.osp_authorization_workflow.name
  - decidim.events.budgets.pending_order.*
  - decidim.events.users.user_officialized.*
  - decidim.events.verifications.verify_with_managed_user.*
  - decidim.meetings.meeting.not_allowed
  - decidim.meetings.directory.meetings.index.all
  - decidim.meetings.meetings.{create, update}.{invalid, success}
  - decidim.scopes.global
  - decidim.scopes.picker.*
  - decidim.system.organizations.omniauth_settings.{france_connect, france_connect_profile, france_connect_uid}.*
  - decidim.system.organizations.omniauth_settings.publik.*
  - decidim.verifications.authorizations.create.*
  - decidim.verifications.authorizations.first_login.actions.*
  - decidim.events.initiatives.initiative_answered.*
  - decidim.initiatives.create_initiative.select_initiative_type.*
  - decidim.resources.initiatives_type.actions.create
  - decidim.proposals.omniauth.france_connect.external.{link,text}
  - decidim.proposals.omniauth.france_connect.forgot_password.ok_text
  - layouts.decidim.data_consent.details.items.*
  - rack_attack.too_many_requests.*
  - activemodel.attributes.confirmation.*
  - activemodel.attributes.mobile_phone.*
  - decidim.admin.participatory_space_private_users.create.*
